(lp0
(dp1
Voverview_polyline
p2
(dp3
Vpoints
p4
VeaytG|`b`Mg|B|yGwZp_BbBlI|m@d]`sAvp@tnBjoApi@~z@pM~qB~VpmAFd|@_I~pDrGbrCvw@hkCpuCl|HrSryAps@dkBxv@txCjbB|qEwGv|BbAvtCr`@xgHvqA|uD~On`@lTfF~fCcq@voAkU~b@~U|wAzkEjzD~dMnfAznCbhD|kEbn@xcAvpFpuNrq@`{CvxBnfFzt@h~Apd@h]dkCpjJffAbrDhq@lsAv{@ffBfbAdpCpjEraLrxBjjHfb@x}CzEhsE~t@~uCvOncDaFxvEiq@zfDkc@d}AuC|q@vf@nnDxdBvbHzmEbiOxxA~aF~|A~hF|Ynr@tn@pPf`@pLnM~RddCjmIttHvkVzfAfdDjrAhaDxrArzCdwEfyI`fD|iG~jA|wBjfAvx@`eAf`A|gAbkBveD`_Gbj@tnCxyEreGpiFnfHvxAvuBxz@r`BthCtzDp}@d~B|qAbx@da@t\u005crmAjxBfy@nc@xwAk@|o@~vAxJjmAGd_B~[hqBp}@r~@|uAp}AteB~aBnoCzsBrqB|h@lp@pu@ttB`zDlbBrfD`d@loAfa@xtCjAvwC~K|zBpvBtlHhrAx~FsDr|C|HzaCdWt`Dpi@lsCd[hoGxXdnHz\u005cjlGpQlnBbp@xsBnj@bxAph@vc@~}@n`Djx@r|Enf@lsAcDxkBsc@fnC__@~yCmXfeAi^|dAvBtc@vKl|BdQneOr[tnNzRfsNpYhuKnd@|hC~Ez}@eE|qArv@pdDf`@ffC|k@`hItlBxwWx}@ffN}[lkCp`@l|CztA~mInl@rsBb_AxuFn`B|kKnh@b~Clu@dtCppDhyJfh@pjA|EpfA|CbbCbo@`pB~aAlxEzm@`dAjq@~zBph@vaD`If_Bd\u005cpl@ng@ho@hRdn@f[vuC|TfcAhl@fv@hcAdfEri@|hBl`@~eDng@t`Gp[poFleAzfJhPhyByMxz@iU`zAwGhgCx[~nBrh@dwAlI|jBvo@bnBv\u005chbCl@feAeVplAlAxx@~fAj_HjKtzB`RzeE`c@djDvgCtdR`eBhmMziBpfOv^htIjSxaBb{@reChx@z|K`M|}ByU~fA{c@zaAgK|{@h\u005c~pDpzAtrJrJhdBiFxfE|~AvhLlb@|gDvl@vaBnw@hyBdkAtlC`cC|sEw@j}@wSjbAfg@~kH`{@h}Ctv@lkGne@xdDfCxuBcCrr@dcBgZt`BwJ`gAsIbl@uNnZyNbY~T~f@|S|Qh_@dQtd@uArk@jt@b|@xj@`TtYz^bJoFjF_C|BjGp@eEcK_u@cAsI
p5
ssVwarnings
p6
(lp7
sVbounds
p8
(dp9
Vnortheast
p10
(dp11
Vlat
p12
F45.5416328
sVlng
p13
F-73.57983089999999
ssVsouthwest
p14
(dp15
Vlat
p16
F43.6742638
sVlng
p17
F-79.3689632
sssVwaypoint_order
p18
(lp19
sVsummary
p20
VON-401 W
p21
sVcopyrights
p22
VMap data ©2019 Google
p23
sVlegs
p24
(lp25
(dp26
Vdistance
p27
(dp28
Vtext
p29
V543 km
p30
sVvalue
p31
I543109
ssVtraffic_speed_entry
p32
(lp33
sVend_address
p34
V172 Danforth Ave, Toronto, ON M4K 1N1, Canada
p35
sVvia_waypoint
p36
(lp37
sVstart_address
p38
V4064 Boul St-Laurent, Montréal, QC H2W 2T3, Canada
p39
sVduration
p40
(dp41
Vtext
p42
V5 hours 21 mins
p43
sVvalue
p44
I19260
ssVsteps
p45
(lp46
(dp47
Vhtml_instructions
p48
VHead <b>northwest</b> on <b>Boul St-Laurent</b> toward <b>Rue Rachel O</b>
p49
sVdistance
p50
(dp51
Vtext
p52
V2.2 km
p53
sVvalue
p54
I2210
ssVtravel_mode
p55
VDRIVING
p56
sVstart_location
p57
(dp58
Vlat
p59
F45.51715249999999
sVlng
p60
F-73.57983089999999
ssVpolyline
p61
(dp62
Vpoints
p63
VeaytG|`b`Mi@xAcC`Hk@~AaC`He@rAy@`CsClIqBvF}CvIcBxEmAlDGPy@xB_@dAc@jAEJQh@g@vAeBfFyBhGoD~JaBtEq@fBwEvMi@vAq@vBKZUp@WTEJMZ
p64
ssVduration
p65
(dp66
Vtext
p67
V6 mins
p68
sVvalue
p69
I387
ssVend_location
p70
(dp71
Vlat
p72
F45.5280169
sVlng
p73
F-73.6035567
ssa(dp74
Vhtml_instructions
p75
VContinue straight to stay on <b>Boul St-Laurent</b><div style="font-size:0.9em">Parts of this road may be closed at certain times or days</div>
p76
sVdistance
p77
(dp78
Vtext
p79
V1.3 km
p80
sVvalue
p81
I1321
ssVmaneuver
p82
Vstraight
p83
sVduration
p84
(dp85
Vtext
p86
V4 mins
p87
sVvalue
p88
I228
ssVtravel_mode
p89
VDRIVING
p90
sVpolyline
p91
(dp92
Vpoints
p93
Vce{tGfuf`Mu@bCEPIZQj@CJO^Ob@Uh@IVw@xBgA~CyCjIuA~DgF|NYz@wCjIoAnDq@pB_@dAeB`FwA|D
p94
ssVstart_location
p95
(dp96
Vlat
p97
F45.5280169
sVlng
p98
F-73.6035567
ssVend_location
p99
(dp100
Vlat
p101
F45.5344476
sVlng
p102
F-73.61781719999999
ssa(dp103
Vhtml_instructions
p104
VSlight <b>right</b> to stay on <b>Boul St-Laurent</b><div style="font-size:0.9em">Parts of this road may be closed at certain times or days</div>
p105
sVdistance
p106
(dp107
Vtext
p108
V1.9 km
p109
sVvalue
p110
I1897
ssVmaneuver
p111
Vturn-slight-right
p112
sVduration
p113
(dp114
Vtext
p115
V5 mins
p116
sVvalue
p117
I289
ssVtravel_mode
p118
VDRIVING
p119
sVpolyline
p120
(dp121
Vpoints
p122
Vim|tGjni`MYZa@t@[`AcAvCm@fBy@xBk@nBK^I`@q@vDkDvPsDrRMn@wB|Kg@dCGX_BfIqA~GmCdNc@~Bs@vD}@vEUrA
p123
ssVstart_location
p124
(dp125
Vlat
p126
F45.5344476
sVlng
p127
F-73.61781719999999
ssVend_location
p128
(dp129
Vlat
p130
F45.5414618
sVlng
p131
F-73.6399249
ssa(dp132
Vhtml_instructions
p133
VTurn <b>left</b> onto <b>Boul Crémazie E</b>
p134
sVdistance
p135
(dp136
Vtext
p137
V0.3 km
p138
sVvalue
p139
I268
ssVmaneuver
p140
Vturn-left
p141
sVduration
p142
(dp143
Vtext
p144
V1 min
p145
sVvalue
p146
I56
ssVtravel_mode
p147
VDRIVING
p148
sVpolyline
p149
(dp150
Vpoints
p151
Vcy}tGnxm`ME^Ib@G\u005cIZKPKJA@UJQJGBU\u005cMXADG\u005cG`@PHtAx@jAp@
p152
ssVstart_location
p153
(dp154
Vlat
p155
F45.5414618
sVlng
p156
F-73.6399249
ssVend_location
p157
(dp158
Vlat
p159
F45.541375
sVlng
p160
F-73.6420655
ssa(dp161
Vhtml_instructions
p162
VContinue onto <b>Boulevard Crémazie O</b>
p163
sVdistance
p164
(dp165
Vtext
p166
V0.1 km
p167
sVvalue
p168
I133
ssVtravel_mode
p169
VDRIVING
p170
sVstart_location
p171
(dp172
Vlat
p173
F45.541375
sVlng
p174
F-73.6420655
ssVpolyline
p175
(dp176
Vpoints
p177
Vqx}tG|en`MTLXNXP^RVPj@\u005ch@X
p178
ssVduration
p179
(dp180
Vtext
p181
V1 min
p182
sVvalue
p183
I16
ssVend_location
p184
(dp185
Vlat
p186
F45.54029190000001
sVlng
p187
F-73.64278259999999
ssa(dp188
Vhtml_instructions
p189
VContinue straight to stay on <b>Boulevard Crémazie O</b>
p190
sVdistance
p191
(dp192
Vtext
p193
V0.4 km
p194
sVvalue
p195
I384
ssVmaneuver
p196
Vstraight
p197
sVduration
p198
(dp199
Vtext
p200
V1 min
p201
sVvalue
p202
I33
ssVtravel_mode
p203
VDRIVING
p204
sVpolyline
p205
(dp206
Vpoints
p207
Vyq}tGjjn`M\u005cTj@`@FDXPz@`@t@d@~BrAr@^x@^lBdA|@X
p208
ssVstart_location
p209
(dp210
Vlat
p211
F45.54029190000001
sVlng
p212
F-73.64278259999999
ssVend_location
p213
(dp214
Vlat
p215
F45.5371331
sVlng
p216
F-73.6447551
ssa(dp217
Vhtml_instructions
p218
VKeep <b>left</b> to stay on <b>Boulevard Crémazie O</b>
p219
sVdistance
p220
(dp221
Vtext
p222
V0.4 km
p223
sVvalue
p224
I441
ssVmaneuver
p225
Vkeep-left
p226
sVduration
p227
(dp228
Vtext
p229
V1 min
p230
sVvalue
p231
I29
ssVtravel_mode
p232
VDRIVING
p233
sVpolyline
p234
(dp235
Vpoints
p236
Va~|tGvvn`Mt@VTJZNf@XbEbCNHHDh@ZTNJHxCdBd@VB@VRZRJHPN
p237
ssVstart_location
p238
(dp239
Vlat
p240
F45.5371331
sVlng
p241
F-73.6447551
ssVend_location
p242
(dp243
Vlat
p244
F45.53353310000001
sVlng
p245
F-73.64712949999999
ssa(dp246
Vhtml_instructions
p247
VMerge onto <b>Route Transcanadienne O</b>/<b>Autoroute 40 O</b> via the ramp on the <b>left</b> to <b>Autoroute 15 S</b>
p248
sVdistance
p249
(dp250
Vtext
p251
V3.5 km
p252
sVvalue
p253
I3492
ssVmaneuver
p254
Vramp-left
p255
sVduration
p256
(dp257
Vtext
p258
V4 mins
p259
sVvalue
p260
I231
ssVtravel_mode
p261
VDRIVING
p262
sVpolyline
p263
(dp264
Vpoints
p265
Vqg|tGpeo`Mh@RDBHDZRf@Zn@\u005cNH@?@@V?~@l@@?fAl@x@b@`@Tb@Tb@TXNDBTLDBLJPJPL`@VRNd@Z\u005cVv@r@JJ`AbAd@f@tA|ARVv@r@r@j@ZPFBTJd@Rn@PNDF@ZFt@H|@Hp@FxAPVBVDXDF@NBn@N|Ad@z@ZjAd@jAd@rDhBnAp@vBlAtAv@bDfBRL^Pf@XHDdAl@dAj@nBjAzCfBlBhAtD|BJFjBhA~CjBx@b@tFzCn@`@bEpBhB`AxAz@bB~@|Ax@j@ZrBfA`@TVNFDj@XZNZNnBdAzAt@vBdAjAj@hB|@tBhA\u005cTZPJHXR
p266
ssVstart_location
p267
(dp268
Vlat
p269
F45.53353310000001
sVlng
p270
F-73.64712949999999
ssVend_location
p271
(dp272
Vlat
p273
F45.504842
sVlng
p274
F-73.6648005
ssa(dp275
Vhtml_instructions
p276
VKeep <b>right</b> to stay on <b>Route Transcanadienne O</b>/<b>Autoroute 40 O</b>, follow signs for <b>Autoroute 520 O</b>/<b>Ottawa</b>/<b>Gatineau</b>
p277
sVdistance
p278
(dp279
Vtext
p280
V34.1 km
p281
sVvalue
p282
I34069
ssVmaneuver
p283
Vkeep-right
p284
sVduration
p285
(dp286
Vtext
p287
V21 mins
p288
sVvalue
p289
I1248
ssVtravel_mode
p290
VDRIVING
p291
sVpolyline
p292
(dp293
Vpoints
p294
VgtvtG~sr`MT\u005cNTDHJPJTP^Rd@HTL^Lb@LVJLZp@Xf@X`@\u005c`@^\u005cZV\u005cRNHPHXN`@PXPPHNJHFFDHJRNVVVXVZ\u005cb@^h@FJdDnE`AnAnBlCnCvDz@hAzCdEj@x@l@z@LTV\u005c`@j@v@nAb@v@Zn@Vn@Xp@Tj@Vv@h@pBR`AJb@F^Jt@BNLdAHn@H~@HnAF~@@FDbABz@FjDBvCBxCDhET`UBvAFfD@bAD`A@ZBZPxCRjCZrCPtAT`B@J\u005cjBb@`C^fBdBnH|@`Et@lDlCzLXpALl@TbAnBzINr@vAvGrAfGn@xC\u005chBF\u005cTnATfBPvAPlBPtBLvBHfBDvBBzA@zA?nBCjBG~C?BEjBE~AMlFOxEI|CG`CKtDGrCA|@OzFe@tRIrDQrHOpFWlKOzGEzA[jMI~D?@AFAp@SxIC~@G~BWrJAj@MpFObG?PErCEpCAfB?JAp@?t@?vA?zDBbC?^?RDpCDtCFnC@h@HdDBr@N~FH|DNlFRlIBt@V`JThIHxCBpAFtBF|BB~@DdBRxHBh@F|BBnABpAFxBH`EL~CJpBLnBNpBJdAN~AFf@@HPvANjAPtAPbA^tBX`BNp@b@xBXfAj@|B@DNf@Ld@d@~Ax@bClBdFr@jB~FnOvC~HdArCr@hBdBrE`JpUNb@fBpEdBrEdAnChFjNdCzGxFfOrFzNfFzMjCbH|@bCRj@l@bBdAjCnA|CbA`ChBpEtAlDjBrENXHNP^z@xBp@`BlAvC`BdExClHbAbCxDnJ~Mv\u005ctAdDl@|AbF|LN\u005cxApD`B`EZt@|BxFnA~CbAbCfDjIp@`BZt@x@pBZz@FJDJJTRd@HVN\u005cRh@Rn@ZdAh@jBX~@Lb@XlAT~@Nr@Jf@FZVzADT^vBj@xEf@`DRvAfA`JHp@j@pEz@xGHn@@LrCxTzAtL\u005c|BVhB`@~B\u005chBVlAV`Ab@jBh@fBxBzFVp@vC~H~@dCz@zBn@`BzDxJ~DbKb@hAvDxJ~A`ErAlD`DjIdDnI|@|BvCpHn@xAdBrEbDnIZv@`@fAbAlC~AbEDLvAvDz@dC`A|CRn@t@~BpAvEdA`E`AhENp@b@jB`AzEh@vCFX^xBZlBXbBJr@`A~GzAtKd@tCXlBp@rDj@zCv@zDJ^p@zCTbAd@bBb@bBh@`Bf@~At@vB~@dCv@nBp@zA~@vBJR\u005cx@pAnCjBjEtA`Dj@rApBtEb@hA~@rB|GtOxB~ERd@@BvCzGRb@vA`Dx@lBrAxCx@jBHR~@xBv@dBP\u005cvAfDrAxCRd@|@rBvB|EbA`CLVfAfCzAjDR`@f@lAZr@\u005c|@\u005cdA\u005chAXbALh@Rz@VnALp@N`ANdALfAD`@JdAFv@FhADx@@\u005cDlABrA?fA?h@C|ACrAKpCAb@O`EI~BElASrFK|CMhDUdG?FMbDGvB]nJQ|EUnGATGtBM~CElAS~FA@Cp@Cp@MxDCn@KvCCp@w@hUCf@MpDCx@OtDKpCMfDA\u005cCr@Cn@EhBCzA?~A?Z@v@@j@Br@FxABx@JpCPjEFvBHtBj@|K`@|K@R`@tKBr@RfFP`F@PRjFBl@TfGXzHNzDRdFH|BJvCBr@HdBBp@T|FBr@XvHRvFBp@Br@Dv@RvFLbDf@pNVfHFnBDr@H`DVzD?BFp@Dp@JnAR`DV`DFn@Dp@LrAFbAFp@TtCDp@NjBPpCPtCFr@TpDJzBBVPfCLhBHtATfDj@jIVlDNfDJ~AhBbVLfBb@pFVjDVzDh@lFHn@?Fd@pDLv@^bC\u005cjBh@jCZtAh@xBlAnEZfAt@rBJVdAtChLlZ|AvDj@xAhBzEZx@`@bAxMd]rDpJrDpJzA|DjBzEjAxCb@dA|@`CDHv@vBz@hChApD\u005cjABJn@hC`BrGRx@Rz@~@`E
p295
ssVstart_location
p296
(dp297
Vlat
p298
F45.504842
sVlng
p299
F-73.6648005
ssVend_location
p300
(dp301
Vlat
p302
F45.4012229
sVlng
p303
F-74.0574201
ssa(dp304
Vhtml_instructions
p305
VTake exit <b>32</b> on the <b>left</b> for <b>Autoroute 30</b> toward <b>ON-401</b>/<b>Salaberry-de-Valleyfield</b>/<b>Toronto</b>/<b>Autoroute 20</b>
p306
sVdistance
p307
(dp308
Vtext
p309
V1.1 km
p310
sVvalue
p311
I1113
ssVmaneuver
p312
Vramp-left
p313
sVduration
p314
(dp315
Vtext
p316
V1 min
p317
sVvalue
p318
I41
ssVtravel_mode
p319
VDRIVING
p320
sVpolyline
p321
(dp322
Vpoints
p323
VslbtGzi_cMFHPZb@fAh@jA^n@LTf@v@Zf@l@r@JLb@d@\u005cZr@j@XTf@Zj@Z\u005cN\u005cNNFlA`@`AT`AJfAFF@~@?b@A^AXCRC`AMlAW~DeAtAa@~Ac@XIlA]|Aa@TCNA
p324
ssVstart_location
p325
(dp326
Vlat
p327
F45.4012229
sVlng
p328
F-74.0574201
ssVend_location
p329
(dp330
Vlat
p331
F45.392207
sVlng
p332
F-74.0596858
ssa(dp333
Vhtml_instructions
p334
VContinue onto <b>Autoroute 30</b>
p335
sVdistance
p336
(dp337
Vtext
p338
V2.7 km
p339
sVvalue
p340
I2713
ssVtravel_mode
p341
VDRIVING
p342
sVstart_location
p343
(dp344
Vlat
p345
F45.392207
sVlng
p346
F-74.0596858
ssVpolyline
p347
(dp348
Vpoints
p349
Vit`tG`x_cMp@WdDaA`Cq@r@Q|DgA\u005cK\u005cKfYqHrDaAdGgBbFqAhKwCp@OLE`@KbAYBAbFsAjCs@lD_AxHsBfEkAvSwF`@KfBg@jCq@
p350
ssVduration
p351
(dp352
Vtext
p353
V2 mins
p354
sVvalue
p355
I96
ssVend_location
p356
(dp357
Vlat
p358
F45.3686121
sVlng
p359
F-74.0508455
ssa(dp360
Vhtml_instructions
p361
VTake exit <b>5</b> to merge onto <b>Autoroute 20 O</b><div style="font-size:0.9em">Entering Ontario</div>
p362
sVdistance
p363
(dp364
Vtext
p365
V30.1 km
p366
sVvalue
p367
I30100
ssVmaneuver
p368
Vramp-right
p369
sVduration
p370
(dp371
Vtext
p372
V17 mins
p373
sVvalue
p374
I1019
ssVtravel_mode
p375
VDRIVING
p376
sVpolyline
p377
(dp378
Vpoints
p379
Vy`|sGx`~bMj@?D?v@Oz@SpCi@B?~A[~A[t@Ob@IFAZGhDm@lCg@l@In@Kn@El@En@CNARAb@?bA?h@@d@@\u005c@H@T@`@Dl@F\u005cDf@Hn@J|@Rl@P\u005cH`@Lh@Rb@PRHf@Rn@Zj@Zx@d@z@j@j@`@^XFDTRFFTRNNv@t@Z\u005cb@d@VZ\u005cb@l@x@f@p@t@lAVb@FHXRf@hA\u005ct@z@bBdA|Bb@dAj@vA\u005cz@|@|Bx@`Cz@hCzAzELb@Rj@tArEhCxItDxLpDpLRl@`BpFhJ|YvElO`C~Hf@|Af@~AtHlVdG~R^lAVx@Tr@bBnFpGvS~BzHvGdTb@vAPj@zA|ErPvi@jBfGfIzWdUvt@`Kd\u005cp@zBd@vAZbAfDvKxGpTz@nCjArDtG`ThCnIHTdHtTxInYzBlHdQjk@pDrLl@nBlAxDtBzGv@|BdAdDnBzFxAhErA~Dd@vAtFlPrDvKPh@Rj@xAnEfD|J`CfHrDrKj@~Ad@hAN`@JT\u005cv@x@jBh@dAR^^t@HN^p@bAbBn@dARZx@pAlAlBx@nArBbDpArBTZf@v@hBnCnAjB~BlDbC~DbEnGl@~@\u005cd@dChDtBlCdCvCNPV\u005cX\u005cxAlBdFtGpXf]bKhMjB|Bv@|@dC~C`EbFlOlRtAdBhAtAVZ~O`SzBrCvQ`U`AjAtBjCRVbD|DtAdBvDrEb@h@VZ\u005c`@p@x@l@v@bApABBn@x@p@|@Zb@f@r@bA~AjAnBt@rAdArBRb@Rd@\u005cr@JVN\u005cZt@Zv@Zx@Xv@Xt@Xz@j@bBx@fCx@jCrAdEpAbE`@lAFPf@~Av@dCdZj_AFLJ\u005cbGbRPj@xDtLdGjR^dAb@lAb@hAnAbD~AvDfEfJp@vAXj@h@fAzAzClDhHdBpDpB`EzBrEpBfE\u005cp@vAfDt@hBvF~NhInThBzE|ChIpJbWt@pBh@rARh@xLt[nKbY~FtOx@rBbBbEvAfDt@hB`A|BLXbDzHhBnEtEzKdGxN|@zBbGpNjDlIj@zAPd@J\u005cDHf@~Ar@|B^pAPn@x@hD\u005c|Ah@pCz@bFzBnMzEtXdBpJv@fE`@xBrArHp@rD~@nFt@lEPbANt@PdAHj@Pz@Nn@Lf@Np@j@pBJ^j@~A\u005c|@Xn@Tj@r@zAZr@nAnCvAbDxA`D`BlDrMtXdDbHjPr]`L~UfDhHnC~F
p380
ssVstart_location
p381
(dp382
Vlat
p383
F45.3686121
sVlng
p384
F-74.0508455
ssVend_location
p385
(dp386
Vlat
p387
F45.2085158
sVlng
p388
F-74.3484867
ssa(dp389
Vhtml_instructions
p390
VContinue onto <b>ON-401 W</b>
p391
sVdistance
p392
(dp393
Vtext
p394
V427 km
p395
sVvalue
p396
I427298
ssVtravel_mode
p397
VDRIVING
p398
sVstart_location
p399
(dp400
Vlat
p401
F45.2085158
sVlng
p402
F-74.3484867
ssVpolyline
p403
(dp404
Vpoints
p405
Vgx|rG`exdMf@fAx@lBf@nA`CdGXt@d@rA~AdEdBrETh@pBlF`AfC|@|Bv@rBt@lBtAnDjAzCFPhAxCRf@dBpEzCbIvArDxC|H~@`CpCnHzB`GrBnFlB`FpCnHpFpN|ChI\u005c|@nAbDrCpHHRVp@Xp@JVLVP^Tb@\u005cj@Zf@`@l@`@f@VXZ\u005cb@`@b@`@JHDBRNd@ZZR\u005cPVNb@Rl@ZpBdAr@^zBjAf@VtAt@lAn@nAp@nAp@t@`@ZP^Td@Zb@ZRNPPTTRPZ\u005cTXTVRXNRPXT^R^LTLVJVLV?@JTJVJVJXJXHXJ\u005cNj@Vz@d@jBh@lBd@hBnAxEbBlG~CnLrB|H^tAr@jCl@~Bt@lC`AtDzBpI|A`GlBdH~@jD`ArD|@bD|@~Cn@zBPh@vAfFpBbHpCtJzCnK^nAxD~MpDfMpCnJ^rAzCjKd@bBjA`E~@`Dh@hBr@bC|B|HfCxI|@~CfArDl@rBfAtDz@vC^pAjA`EpArE`AbDhBjGtAzEt@fChAxDt@hCjBnG`@vAr@bCvC~J|@`D`BtFnBzGjC~I~@zC~@dD~@`DLb@|CrKzBrHNh@Vx@|@`Dv@hCRt@~@`D~@bD~@bD|@vCvA`FRp@t@fC`CdIdB~Fx@lC^pAx@dCnA`E|@vCt@fCx@lCdAhDx@lC\u005cjAPh@t@bCb@xAf@~Aj@lBd@vARl@x@`Cr@nBx@nBf@hAb@~@vArCj@bAl@bAZf@h@x@V`@NT^h@^h@r@~@v@bApAzArA~AvA`Bp@z@fBrBxAdB~AlBvAdBtA`BvBfC`@f@t@z@`AlAr@|@n@`Al@~@n@`Al@`Ax@xAx@|Ah@fAbAzBZt@\u005cx@^bA~@bC`@fAVp@Zz@tAvDBHpAlDx@zBXv@bBtE`CvGhCbHdArCBH`AlCHThCdH\u005c~@dAvCz@~B|@dCt@tBf@tArAtDz@bCrArDhBfF`@fAx@`CfAxCpApDv@zB|@`CpAnDfAxCx@~Bz@|BhA`D\u005c`AfAvCjFzNnAlD`AnCdAtCRh@`@jAjBbF~BtGn@dB`CvGfAzCnAhDz@~BhBdFdAvCx@|BhBbFTl@hA|CpApDfB`FFPfC`HnCtH~Md_@fB`FrArDDHnBrFbF`Nz@xB|@|BjArChArC|@zBz@tBN^rAfDpB`F|@|BxA|DXp@Th@bAdCfIlSfBnEzJrVjBvExApDPd@zCtHtBlFlFrMRf@hBnEbAfC`EbKv@nBpB`FhCvGzC`HxA~CvCpHbCjGr@dBlA|Cj@|A\u005c`ArA|DbEdN~BvHhFbQxA|ExAzEjCxI~EfPh@`B\u005clAx@hC^pAfApDnHlV|BtHxBlHhGpSb@rArBzGtBbH`@tAPj@jBdG~EhP|@zCrDvLrAjEvEpO`A~CpBvGj@lB`DlKzC~Jp@xBtB`HtBdHDLj@lBd@dB\u005cbBPz@RrATfBPvAPhBVbCBVVbCv@zH`@dEbAjKx@hI@HJfALfAr@hHp@bHTtBvB~S\u005cpDRtBN`BNdBDp@D|@HxC@b@BpC?FDxD@bA@p@?VDpE@j@HbJ@j@LpMHtGHnJBrBNzOL|KBxCFnETrTFvFHvQPjN@VJhI@rBBhBB~BBvA@d@@VJtCF~@Fz@JvARxBHt@J|@ZrBd@lCTfATdANn@J`@BJXdAh@dBJ^`A~CdAnDvAtE^lA`A`DtAtEhCtIjCvIb@xAdClIvCpJxFjRzBnHf@dBj@lBRx@XlAd@pB`@nB\u005cnBF\u005cTpATzANjALbATrBNvAJpA@HHlALdBFhAFhAD~@FvBFrCFxCT~OJxELjJFdEVfPNtI?ZTrNTzMH~DBnBF`EBhA@hAHxFFhDLpIBvA@rB@~@@dB?pACvC?FKjFK|DU`KS~HQnHc@zQOjGIjEUhJKfE_@nPOlFUxKA^KbEIxCQ`FIvAGvAKzBQjCEp@IdAYlDQjBQhB]jDe@|Dg@~Dq@pEAFw@|E{@zEg@dCa@lBm@nCe@lBQv@iArEs@dCk@pBcDlLA@{GnUADM`@q@|B{DbN}ChK]fAkC`JiE~NY`AsFdRgAnDyBvH{BtHITGVa@zAs@lCk@`CGTe@dCI^UrAYjBIp@[nCWfC[lECp@Ex@CdAGfC?f@AhAAdC@tA@~AH|CJfCFnAF|@Hz@LbBBVHt@Hz@Jz@XpBv@xFn@rEhBjMVdBrFh`@Hb@@J~@xGzDrXh@zD@DPrAv@pFlAbId@tCX`BTrAFZLp@XxAd@|Bn@zCv@hDt@vCBNx@dDnAdFnAbFnAbFxDpOdAfEfBfHx@`D~BjJ|DbPx@bDbAdEZpAhFxSNl@|Ij^lJx_@^zANl@`AzDZtAfFxSpEtQXlAFRnDvNXfAn@jCxBxIlG|VhAnEh@rBn@xB`@vANf@v@jCtAzEzAjFtBhHNb@@Fd@vA~B|H|@~CBHxBpHrCpJ\u005cjA`FrPzEdPp@~BxDpMrB`HbFbQtB`HzAdFn@vBbAjDdCxIpArErE|OzEhPrDbM`CfIPl@Vv@tFdRhCvIvC|J|@zCr@`CPj@pAlEz@rCjDnLJZnA`E~BhI`EfNvAvETv@vEvOZfA|BzHrDxL|DlMhGtSx@pCTn@vDhMvA|EPj@Lb@lBtGV~@XfA\u005cjAlCpJ\u005cjAdBzF^nARr@~@`DjBxG`AdD~@fD|AlFf@fBZfAf@dBfBhGf@dB^vANb@@FfAtDn@xBp@`Cx@nC`AfDPj@nBrGv@pCv@hCxBlHpB~GtBjHr@vBh@bB^pA^rAZ`A^rA`@rAJ\u005cZbA`@rA^nAb@zA^lATv@^lAZdAV|@Vx@XdAVv@Vz@ZfAL`@Rp@HXFPRn@X~@FRLb@^lAj@pBh@dBxCpKrCnJtBdHxC`KjA|DtA|EjA`EnCnJPj@Rr@r@bCxArERj@Rp@lIdXZ`AjB`GvDlMn@rBr@bCpBxGlJp[~B~HxC|JPj@nAdElAfEPj@rHbWlArDZx@Tj@Xr@d@x@j@dA^p@d@r@f@r@h@t@~@lA^`@FFj@h@l@h@fAx@l@`@n@`@FD^Th@T^Nz@ZbAX\u005cJLBhAVv@LfFz@xS~ClCb@b@FpDh@hCd@tAVh@LPD`@Lf@Rx@\u005cfAh@VNZPbAn@fAv@ZTXV\u005cZFF`@`@`@d@Z\u005cd@n@l@|@h@v@`AdBR`@Th@^x@Pb@JVFNTn@Z`ArBzGHVf@dBnDtLjBpGdB~FzBvH`@pAtJf\u005cBLbB~FzBrH`@vAV|@bBvFpAjEhA|DVv@hCzIvA~E~ElPvHxWpClJ`@tA~Jn]lDrLnKl^lHrVrCpJrErOPj@fGvShJh[xI`ZpD|L@DvCfJHVxEpNPj@rDzKrA~DjElMdA`DfEfMdBfF`B~EvCxIFRvCvI|BbHj@`Bt@vB`IhVbCnHvC|I~A~EbBnFbDjKrFlQ~HvVfGdSTv@Jd@l@nB`GfRdAdDbMta@L^lD~LrAjDNl@rMxb@pC|IfBjGfE`N|FdRvFvQh@bB~DzL`CnHlM`a@rNvc@Ph@t@~BdChIlAjEPl@bIjYh@rBvFpTz@dDtDhNTz@dF~RrIt\u005cRt@nCpKzBnIzBlHxBhGfBjEdF|L`@~@n@zAbAfC`D`IhHbQRh@fFbMTf@fH`Qh@nARh@bGlNzBpFpHpQvSpg@BDdBfEhCjG|AvDp@~A?@f@lAxN~]Rh@nMh[Rf@Th@zFlNRh@Rd@z@rB|ArDt@jBBHTf@Rh@DHf@pAhBnEN\u005ctAfDxBjFRh@rC~G^z@lAvCz@pBl@tAfC~FnAdCfBhDxAjCdAnBFLhJ`QnA~BZl@DHx@zAr@rAr@tAbCrE|@`BrClF^r@jBnDpA~BdAnBbApBzAnCdAnBn@jAlA~B|CzFvDfHpCdFfCzEtBzDxAnCdE|HVd@lAzB~@fBnJjQhHzMtEtIrBxDfGbLrAfChBhD|BfEP\u005cnElI|DlH|BhEhAvBzFtKrEnIxAnC~EdJrBxDdApBpChF?@fCzEjDpGvAhCp@nAzBfEv@vAnA~BtB~DFHh@bAz@|AxAlCTd@Vd@rAdCnBpDvDdHVf@|DpHVd@`@t@h@bA`AfB`AfB`CjEh@dAd@|@`@t@fArB`AlBrD|GnBlDBDz@~An@lADHvAlCj@jAxB`EhArBhAvBzCxF|@~AlFxJdCrE|@bBj@bA`@v@j@fAtL|Tj@dAv@xAf@~@v@xALVpA~BrKbS~BnEbCpE@?nA`CnBpDz@~A`@r@Vd@`@v@jBjDJRvCpFbCpEnDtG\u005cp@Xf@BFr@rAr@pAz@`Bh@`Ap@nAn@nAdAlBxAnCxAlCdAnBtD~G`CnE`ClEvB~DlBlD`@t@j@dAtAhCNXrD`HvAfClC~EbB|CbB`Dv@vAh@bAz@|At@vAx@xAj@dAj@bAh@bAx@zAt@vAHN`@t@l@fAh@`Aj@`A\u005cl@^j@\u005cj@^h@\u005cf@`AtAz@jAx@~@p@x@x@z@l@l@xAvAdA|@r@j@`Ar@rA|@zA~@bB~@vAt@|Av@x@`@x@`@lB~@rCrAfD`BfD`BtBbA|Av@`@RLF~BfAVLrE|BvCvAxBfA`Bx@n@\u005c|@d@zAz@lAv@`Ap@PLPLzAjApBjB`A~@h@h@dAjAlAxA`@j@h@p@n@~@x@pAxAdC@DpAvBfAfBf@|@xBhDNVPVd@v@bAdBvA`ChAlBv@rA`@p@x@vA`AdB?@~BxDhAlBrA~BVd@z@xApBhDp@hA^n@Vd@Xb@l@bABD`@r@rDhGdEdH~AlCfBtClBvChAlBdEdHj@|@Vd@`@p@~B|DlBbD^n@rBjDvDpGpAxBxI`O|EjIXb@pFhJXb@xBvDjAlBXd@z@zAfB|Cv@pAVb@rC|EVb@@@Vb@bBrC`A~AFL`CzD|AjCXb@p@hAt@lAR^Xf@tA~BzBvDt@nAPXvC`FnCtE|@xAhLxRhBxCj@`AjBzCtC|E~IfObBtCfFvI`A`BLTh@bAr@tAf@bAVn@h@nAZt@d@hA@DRj@Xt@\u005cdA`@pA`@pATz@FP\u005crAZpAVjARz@DTLn@BHVrATrALx@V~ABNF^RnARvA\u005ctB?@Jl@L~@F^TtAXlBJj@NfAZpB\u005crBVhBXhBTrA\u005c|BTvAZrBZpB@JXfBZrBZlBZrBZpBRrA\u005cvBXhBTrA@@Jl@Jf@XrAXtAFTZpATx@\u005cpAJZFRHX`@pA`@lA`@jA`@fAf@lAb@fALVXn@f@fAj@hAf@~@LTj@dAj@~@LPNX@@RXd@t@n@|@V\u005cT\u005ct@~@l@v@~@lA`AlAp@z@`AlA^f@n@v@|BtChAvAtBjCfJlL`D~DvFhHfC`DjCfDdDdE|AlBvCrDnBbCZ`@DDdC~CVZjCdDxKfNbEjFjFvG`@h@zCxDbFnGZ^`FnGrExFrMlPb@j@bJfLnHdJx@bAtCnDZ^|KbNbAnAv@bA`@d@b@j@NRl@t@~@hAl@v@bAnAv@bAzC`EjCfDvFdHdGzHvFxGbCzCxCvD|CzDPRTZ|BrCNRZ`@nA|AnBdCNPnChDpBfCrAbBb@h@rEzF|@hAfElF`AnArIrK~KzMdH|IdDbEjMdPfEhFbEfFlAfBl@`ApD|FdCbEh@v@lChEpCnEV^d@v@\u005cf@j@~@n@`A?@z@rAbBlCrAtBZf@x@pA`A|ApArB|AdC|AdCxA~BzAbCdBrCpApBdAdB`GlJ`AxA|@pAv@dAjAxA\u005c^t@x@pArAdB~AtAnAXTpBbBtBjB~BnBvAlAj@f@z@t@hAdAx@z@jAnAj@n@|ApB~@nAdBjCvChFpAdCz@`Bx@|AnAfCb@v@hBjD`DhGvE~I^t@hAzB~BpEjDxGbBbDd@`At@vA|AxC\u005cr@tAlCdApBVf@Zn@x@`Bb@x@lJ|Ql@jA~BpEb@z@n@lAJR`DlGFNtAhCn@nATb@Td@h@dAn@nAlAzBR^fAnB`@n@PV@D`A|A^l@z@pAlAhBHJ~@~AvAxBpBtCPTZb@`CnDnCbEv@nAbBhCZj@^l@|G|Jz@nAb@r@z@nAl@|@rApBPTVb@x@lA`@j@p@dA~@rAXb@\u005ch@nCfEdBlC\u005cf@Zd@bA|AvAtBn@`AzA|BrAlBb@r@R^x@jAp@dAx@lAlBrCfAzAf@t@`AvAnBzCf@t@fBnCV`@l@`AdF~HvClEfDjFdD`FRZhAfBZ`@PNHHRRJNhAdBvAxBLV^r@dArB@?Th@n@tAN`@Th@DJhAxCVp@pCrHHRRh@hCbHnAjDvGlQL\u005chBzE@FhDdJfEbLd@nAfC~GVr@nAfDHTz@tB`@`ATd@f@bA|@`BZh@LRV`@n@~@dCbD`@h@`DzDt@z@b@d@`AdAp@j@h@f@pBzAZRZRh@Zh@Xj@XB@z@^hBt@t@Zv@XfC`A~OdG`@NhDpA`@NfC`A\u005cLlDrA|B|@d@R\u005cNHD^PfBz@vBpAhBjAn@f@dCpBhAbAj@j@h@h@t@x@hAnAvAjB~AtBx@pAXd@Zf@h@~@|Tba@hMfUVd@fAlBxK~R`CjE~DlHPZ|DdH`@r@d@v@|AbClA`B`@h@vAbBJNnApAdAdAv@r@|@t@z@r@NL~AjAx@h@jAp@v@b@jAl@FBx@`@t@ZpAh@h@RVHdBj@`AXp@PPDfB`@pATn@Jn@Hn@HhAJd@DH?XBz@D~@BfABhA@z@?l@Cb@Ad@A|BIb@ARAhGSfACb@C~BI|DQPA`M_@fFOzFQtBGr@Ap@?|@Dl@Ff@Hj@Lh@Nh@P`@Rh@Vj@Xb@Xf@^^\u005cf@d@\u005c`@d@h@X`@FHX`@xA~Bl@bAd@v@DJ\u005cl@f@dAZl@`@x@z@nBz@xB|@bCTr@|CjJfEbM|AvEjAjD~@pCt@`CJXNj@L`@f@fB\u005cnAf@vBf@~BNv@Nv@Nz@@HV~AZxBJx@DZBTPvAPjBN`BBVRjDH~AJjCB`A@\u005cDpB@x@?d@@lC?xB?p@Ah@C`BCpAGpBI|AGvAUbDM`B[fDO|AOdBGp@Gr@QtBKjAEh@?FK`CGrBGbD@nC@bB@n@?@NfE@LJtARrC@DZjCXtBBXR`Bh@`ENjANjAxArLpGxg@vCtUHn@~@pHHf@NdATvAVrAd@dB`@nAb@fAh@hAf@bAz@pAnA|AbAbAjClC`NhNxO`P|E`FfAhAVT\u005cZ\u005cZBBx@v@n@n@xAxA`AbAp@r@DBd@f@n@p@xA`Bl@p@p@r@fBnBlBvBZ\u005cbEvEvA|Av@|@XZpJvKZ\u005chDzD\u005c\u005cdExE|BjC`CfCdCpCr@x@xBbCPRbClC~AhBd@f@JLRTn@t@jDxDtB`CnAvAt@z@pKtLfDvDvCfD`CjCvBxB`B|AHHlD`DTPv@t@^ZnC`CdA`AtAlAhAbAnCdCpAlAVTfA~@jB`Br@p@zArAhB~AjB~APN~BhBpBxApA`AdD`C`LtItCvBfEdD^X`HlFlMzJtAbA\u005cXhEbD`ChBd@\u005cb@\u005chIhGj@b@vAfApBxAzAhA`ChB\u005cXXRjHpFr@h@rFfEfDdCnBxAtGbFdDfCtCxBhAv@v@f@@@|A|@z@d@h@XPHhAh@zBz@bA^xAb@HBbBb@\u005cHnBd@`B`@`@JvFrApD|@~@Rv@RfDv@|Cr@jDz@hDv@l@NvFpAzUnFfFlAnAXb@Jn@RpA`@d@RVHZN^Rd@VPLf@Xd@ZRPb@Zd@`@\u005cZhAjAdBnBt@z@LNLNr@x@vA`BZ^pBzBZ^zAbBbAjAr@x@bBlB~@hA`AnAl@z@~@rAr@hADHPXv@tAf@~@@D`ApBTd@LTbAbCfApCt@lBl@xAp@bBn@~Ap@`Bp@`Bp@bBn@`B|@zBh@rA\u005c|@d@jAp@`Bv@pBDHtAfDf@fAP^`@z@h@fAv@zAx@xAbAhBBBj@`Az@tAPVBFTZt@nArArBxA`CxA~BjAjBhAhBvKbQhBvCdC~Dj@z@|@vA~@zAVb@PVfBtChBtCtBhD^j@p@fAFJjAlBh@x@Xb@b@r@fC`E\u005ch@^j@vA|BjAlBhBrCfBtCT^Xb@z@rA`A|AT^BBx@rAl@~@j@`Aj@|@z@tAj@~@j@bAj@bAl@nAn@rAp@zAp@dBn@bBn@dB^lAL^J^d@`Bp@bCNj@^vAn@dCvAnFRt@FRJ^p@tBJVVp@Pb@JXVl@N\u005cHNLXh@fAh@`Ax@vAvA~BT^r@jAdBtC|AhCT`@jBzCbAdB~@~AHL|@zApFhJf@z@tBjDPXbBpCtBjDlAzBrAdCb@t@Vb@l@bAfAhB\u005cl@NTh@~@l@bAz@vArAzBBBrAbC`@r@d@~@DHTf@^|@^|@Rf@d@vA`@lAf@hB`@zA\u005c~A\u005cpBb@lCLt@Hn@Hh@j@fEt@lF`@lC^jCVbB?@ZlB\u005cfC\u005czBn@rEn@nE@Hl@hENjAZtBl@jE@L`AdHj@~DHj@XnBRxAJp@^lC`@pCbDlUjAnIlApI@DT~Ab@bDDZ^hCTdB~@nGj@nEVnBRpBNxA@JLbBJ`BFnAB^@NFhAH|BDzB@rB@rC?tBExCGpD?PYnMEnBMxFMzFMxFMxFQfIE|BQdI?HMhGC~@IzDCnBCpCCvC?lF@vB@xBBlCFnDH|CNnENpDTjEPvCVdDJxAR~BVpCHv@Hp@Hz@XdCBLD`@VjBPrAJp@PtA\u005czBTpATvAn@hD^lBNv@n@vCx@nDLn@^xAb@dBJ`@x@|Ch@fBRr@jA|Dj@lBZbA|@zC|@xCVz@Pj@JZV~@r@~BDP`A|C`@tAn@vB~@`Dz@rCt@fCn@vBDN`AbDxBpHdAjD`@vAp@|Bv@hCxAxEDNvCpJPj@zLda@Vx@l@tB`C~H`A~CdAnDPj@~@xCfBhGvAzExAxEZ`AtCrJFR`BpFPl@|ChKHVfD`LNf@Pj@rAnEfApD`@rAzAfF|BrH@DpGfTj@hB@@|@xCr@`Ch@fBBDp@|B|@zC`A`DPn@f@dBh@jB@FPj@ZlAp@fCv@|Cd@jBRz@Nl@?@\u005cvAVhA\u005cvADT\u005cvAVnAPp@Pz@Lj@@FJf@BJXrAv@~Df@fCF^BLr@tDl@hD`@tBJl@FZ^lBl@hDDRJn@pAhHTpAt@bEtApHf@tCrAjHrB`Lz@zE^rB`@tBnAxGhCfNd@hCNx@Nt@Lv@Lx@XnBPzALtAF~@Df@JfBHtB@b@DrA@zA?r@?z@?DAzBElBGdBInBOjDU~Eq@nOy@fRCn@a@lJGrAqA`[E~@c@dKA`@_@fIQpEGzAEvAA^Cx@Az@A`@?XAjAAlC@zA@nAD`CFtB@d@FpAHpBHjADp@NrBR`CRbC^nE\u005cjEPrBXnDBTtApPbA~LBZPvBFz@Db@ZjELxAl@nHHbAR~BZ|DFx@f@fGlAhO@F`@fFZpDRpCH|@JrAb@jFBVn@dIl@hHh@bHf@bGPpBXjD@LHfAPrBXlD\u005clEPrBPvBTnCDb@NlBTnCf@`GXnDLtANvAPrAJx@PrA\u005cdC`@|CXrAdAvEnBbIHVlEpQrBrINj@ZnAdAjEXnANj@dDfNx@jD\u005ctAXhA^zA`@bBVhATdA`@rBZ`BV|A@FFf@ZxBXzBJdABTHn@Fp@LpAPdCH|AF|ADdAFrAPxFHhC@r@Bt@FbCJnDTjJNlFNxF@f@HfCB`ADjB@VFvBDhBBj@JjDFpBFhBD~@FdBJvBJ~B@ZNnCf@zJb@vIFlAPhDBp@\u005cvGVxEL`C`@|H\u005cfGVdF?@RdEL~BJxBHdBDn@j@dM@Xn@dO@ZNrCHhBF|ARvDD`AR~DZjFJtBDp@H~ANvCFlAT|EJ`B^|HVdFRdE?@TdE?Dd@lJx@|PBd@DbAFjABl@DfA?DBj@H`DDpBF~DBpABzBHzGFbE@l@?BHxFBbBHhE@z@JhEBjBDlA?@LlD@X`@~JLdDLzCHrBNnDFtAx@xSH`BPdEXdHv@zPJnC@DBp@FdBBn@FzAH~B@THpCHpCJxCLrD?@HtBVrHBn@B|@LrCn@dPNzDB`@D`ADz@DnAHfCHxBv@`SJbCFnAHfBVzGXfHDhAH`CRxE?@Bz@TrFFrAJvCJxBHzBDr@DbALvBLvBNtBJxAJvAN~ALrAFv@JhA\u005c`DX|CFp@TnBB\u005cHz@h@jFd@fFNhBPbBRxB`@jEBNt@zHZbDNjBFn@JdAZbDNfBl@vGXjDFj@B^Hn@HhAh@xFDd@Hx@d@dFXrCZhDPbBLvAH~@`@bEf@nFH`ATvBn@bHP`BBTN~AFl@J|@Dd@Hv@DRNvAd@vCPfAZ|A^rBH\u005cz@vDr@jCLb@FRXz@Vz@h@xAnAfDf@pAb@fAjA|CVp@fAxC`@hA~@fC^dAn@dB|@bCx@vBHVd@pAhCbHTn@`JrVRh@nFbOj@~AfAxCvAfEL^hBbF`BjEx@|BRf@BFrArDHTrArDL\u005cv@rBXz@Vp@Vr@Vr@Zt@Tl@Xp@JTLXZn@Xh@@B\u005cj@\u005cj@^j@^f@^f@`@f@`@d@b@b@`@^d@b@b@^d@\u005cb@Zf@Zt@d@dBbAdBbAnDtBLHXNd@Z^XDBd@Zd@^b@`@b@^^^b@b@^d@b@f@\u005cd@^f@\u005ch@\u005ch@NXXf@\u005cn@Xl@Xl@Xp@Vn@d@jA|A~DXv@`@`Ax@vBb@fAb@hARf@d@nABF^~@FRd@jAb@jADL\u005cz@r@hBf@rAnAdDp@fB~CpId@lAxA~DHTjA~C^fA@Bb@lA`@nA^nATr@\u005cjAPr@\u005cpAXlAPv@Lr@Pt@Nz@Nv@Fb@DVRpAb@tC^fC@FHf@DZXjBT~Al@xDx@pFBV`@nCPdA?@N`Af@jDLt@ZtBdBhLb@vCb@tC|CzSfIdj@lBnMz@zFlAlI@@rAdJn@tEXjBp@|E^jC`@lCf@~CdA|Gz@hGr@jEZrBLr@P~@XpAj@pBz@pCBHbAtCl@`BTn@x@lBhAhCZv@n@xA@DzAnDvAbD|@xBh@jAn@`BxAfD`BzD|@tBbB~Dt@bB^~@~@xBBBN`@Xp@\u005c~@Rl@DLTp@Nh@Vz@Lf@Jd@Hb@RdAV|ARzANxALpAFx@D~@Dt@DhA@dA@bA?@?rAApACz@E|AIvCItCA\u005cCzACj@KbDCz@ExAQxFQjFIbDMfEEbBKzC[nKC`AG|AIlBIvAEj@GhAQrBQpBQxAUlBWnB[lBc@hCm@hDg@vCu@hEWvASlAUnAGXeA`Gg@nCg@jCcBjJ_BzI_@tBaCxMETs@zDShAi@|CMl@Y`B}@nFO~@OfAWrBUpBSpBM|ACZMtBOvCc@|HcBh\u005cs@|LMnBUpCMlAWbCWpBUdBAF[hBY~AWlAa@jBQr@KXy@tDsD`PiA`FOn@I`@s@zCq@zCOt@CJU`AWdAOv@St@_@zAW`AABI^On@On@a@bBCHGVUfAYpAMh@m@fCYnAm@hCGTENm@lCeAnEe@nBg@rBMf@a@pA]hAITMZ]|@c@fAs@`BqAnCmAbCiLbUeBlD{@xB}@jCm@`CQp@On@Ov@Kn@UlAQvAQbBO|BI|AATErB?JAf@Ar@@dBDhCFvA@^Dn@Dp@@PNdB`@~CV`BX~AR~@Tz@FPxAvEb@vAXz@^zAR|@Nx@ZdBV`BP`BNdBJhCBbABbA?z@@tC?bA?^@dB@tG?fABvN?P@^DrIDdG@j@@lKBdGHnX?p@@dEDtK?p@FbNBpJ?p@V|u@BxH@lH@vA@fE@tBR~JDzBH|BtAja@RxFBp@PzE|@hWRxFNfEBp@NzDdBlg@H~CBhCF~EBnGH`T?RBlGF`O@p@B|EBlH@vCBjG@xCBnE?@BpEBvCDnGDnFDpFDnF@xB@lA?L@xABtD@tC?N?p@@pABtD@tC@z@@|A@`@BrAHvBf@`MRpF?@NnDXjGVjGRjFJzBj@zMXjHb@`KBz@ZjHBp@HbCHtDP`KPbKb@jUb@jV?FD~B@n@LlFPxJX~N?FHrDJrFPpJNdH?DJdFNnGFpDFdDNrJHtFHnFHlFHnFPlIHnEDxBJnFLnFNhIJrEHpEBv@RfKNlGFdCBhBH|DBp@?DHzENtI^rW@p@LjHPfMHtFB~ADzCDtCXvQLnHFrC@z@JtG?LHbHHdFTfPFjEHfEHhFDnC@fA@r@@dA@H@xBHdHVhUNtMFpENtNHjFJlGRrO@\u005cZfUN|JDnDFdFD`CJlH@n@JhG@b@HnFTlM?LF`DDlDFvDNxKBjBDbCFfGNvKF|CRzM@p@RlMN`KPlLHjG?HLhILvJLhJBrDFzDJxIHtFFdFB~AFjEDtBDnCDdCJrGFdEF~CJvFFnED`CFzCBz@F`CPjEHpBLzBJlBX|FVxFBb@Bb@n@|Lx@bPZfGZxFTjEX~Ft@rNLfC|@`Qr@bNTzDDfA`@~H@ZHhBDr@@n@BvA@z@DdE@X@pAPlQDrFDfE@zCF`G?l@?BT|W?BP~TJpKDtC@rABjADzABn@@FD`AFzAF|@HdAJrAL|AZvCPvAJ|@VdB`@hCLt@VvAp@hDhArFdAnFfAnFRz@r@lDnAbG~@lElClM|@jEj@pC|@lEdA`FDRfArFNr@Px@Jh@Ll@DRTnANx@XnBBL@JFb@DTBX?@Jx@DXD^Hz@VlCFv@JvAFv@@^JpBDz@DvAB|@BtABz@?n@@d@@bBAdDA|@GtCGpBKpCMrBK~ACTSnCKnAEb@QtBQpBQpBQrBMxACXQrBIz@Ej@AJMpCItB?VC`AAtA?zAB|ABpB?BFpAB|@HtAJtAB\u005cJnADd@DZJv@Ht@RvALx@FZF`@Jj@\u005c|ABLb@nBPr@fBfH^zA\u005cvARv@v@xCf@nBfBbH`Il[xC`MT|@|DtP`AzDhArEjAtEfBdHPp@tAnFtApFpAhFH\u005c~AjG`AxD`EfPh@rBz@dDj@~BR|@Nj@XrA^pB\u005cjBf@hDHn@Hn@TjBFr@NxAXpDZ~DZrEDr@HfAHlALtAL~Af@fHVbDLrBNlBHbADn@J|Ah@lHDn@LbBRxCrApSf@bIJ~ApBhYDp@L`BzDdj@fCh^`@~FlC`_@|@zLDp@n@vIDp@`@tFFp@Dp@`@vFx@hKTrCRrChBtUDf@p@`KHjAzAhSz@dMVvDLdA@Jx@xKhAfOHjAjEdn@vA`Sz@zLDn@p@rJtFru@lBrW`@tFDp@V`DHrAtAvS~@hNt@xJdBhUnAvPJxA@ZbBfUJ`BNrBjBtWp@dJb@fGpBfYnAlQz@zLb@fGt@hKbAlNt@hKHlAPvBL`Bn@vIfAlNnBpWh@fHj@hHHlAnGr|@h@dHXdEZdEf@fHlDle@ZdETrCRpCBXLbBJ|AJzAJtATzCdBbVh@dHRvCRnCfBnWf@zFV|CBd@RbCj@zHHfAf@fHL~ArBdYn@xIFx@hAhOv@tKJrAh@~HRhCNvBx@vKLpBTpCHtALzAb@zFLzA\u005cnETdDVdD\u005cvEFp@RrCvBvZZbERvCrB`YzBtZDb@fA~O`@tFdBpUvA|Rp@`Jx@dLr@nJh@vHXrDLzAHhBFdAHtBJpC?NBbB@bB@p@?X?vB?BAlBCxAKrDEdA?JIxAUjD]hE_@bDG`@Kx@_@hCeAxFi@`CgAdFCLsBvJGVy@vDaCzKi@fCg@fCw@~E_@`DSdBGl@?@QpBc@vGCp@Cn@SjHCp@?`E?fABvA@fABhAFvBBt@B|@JrBFn@J`BJtAHz@Hx@\u005c`DDXDb@PnATvAbAvGlAdIj@|DJn@DVdAlHr@bF~BhOp@hE|BrOf@hDdBjLdA|GL~@l@bE~@fGTbB`@hCtAjJfAnH`AzGt@zEd@`DJn@VbBlAfI@DhArHzAdKl@bE@D`ArG@Hx@lFv@lFl@|DHn@RnAt@~EbAxGfApHjAzHJp@RpAf@fDBLrA|Il@`Er@`F`ApGl@`ELv@|AhKz@xFr@~ELv@ZpBdB`LPpAt@|Et@~Er@~Dn@dDj@nCBPHZh@bCVfAd@pBb@`Bf@nBh@dBRp@^lAb@zAXz@ZdAv@bCNh@x@jCt@|BrAhEhApD@BPj@Ph@Lf@rAlEh@fB@?vAxEPf@|AfFbA`DPh@z@lC^nA`@nAl@dBrAnEt@`C^pAtAtE`ApDT~@R~@?@zAzGn@dDh@nC@JhAzGdAlG@JpBxLl@tDjAlHV~ADNl@tDBJb@nCnCnPh@dDb@lC|BjN~EfYLl@`@~BVrAhGp]Jn@TrALv@DZ\u005cpBbBhK|Fx]BPN`Aj@hDlCbP?FjAdHRlAfAxGx@`F^xB`@`CZhBx@bFLv@\u005crBf@dDn@fEn@fEf@hDf@jDf@bD@BxAnJz@|FTvAHl@x@lFVdB`@hCp@pEn@fEn@`ElBzMvAvJv@fFHl@xA|Jf@bD`AzGxCjSdAhHxAbKrAdJ^bCv@pFrAbJv@rFPhAh@lDp@fELt@RpAbAbGZhB\u005cnBV|Aj@jD\u005ctBDPFZZpBn@tDpAxHr@dEfAvGnApHv@pEJp@`BtJ|@nFv@tEx@`Fn@pDh@`Dl@jDRnAp@zDpA~H@Hp@xDvAvIr@bERjAd@rCHf@X`BPbAf@vCr@lEv@nE@@n@xDLp@b@jCJl@r@dEHd@Jp@j@hDfAtGlBdLPdAPbAnD`TfDfSnApHd@lCb@hC\u005cjBXtAPx@Nt@Pp@XlARt@^nAHZHX^lA^pA^fALZz@|BzDbKhAxCz@zBZv@Rh@vAvD|BbGvBvFrAjDj@zARh@Rd@z@zB?Bx@zBb@hADH`AfCXr@lCfHZv@pHzRzC`IbBnEbAhCpDnJVn@l@~A`Tpj@Xv@hAvCtDtJ~AfEJTtBvF~AhEVn@lB`FbCnGbBnEbBnEFJdCtG^bAnAbD|AdEvAbEjAlD|DbL~ArEBJfA|C`@jAxIbW\u005cdAJVX|@tF~O~BzG|AtEj@dBPf@Vt@dAzCTp@|BdGJXtChIHVDJPb@pBfGzD|KDNdEbJ|B`Fb@~@@Bb@z@|B~EvA|Cd@bAp@zAlD|HtA~C`AvBVh@`DfH~AhEJZb@bBZnANp@Jj@TrARhBFn@TvBHjA@PFxBFrBDdHNnVBfCBnC?p@DfE@tCJdFHxW@nA?p@@p@NvQDbFV`ZHhLJdCLrBPhBVrBZrBVvA^xAZjAj@fBvAdE`Lf\u005cvH`UdAzClB`GlAnDr@zBRh@tBpGv@bC|@lCnC`JXnAhAtEhD`PpCxN@HR`AVlAl@vCLl@jClM|EzU`A|EfA`Ft@tDlAjGn@zDX`B|AfKbC~PtAfJRlAZhBn@~Cp@nCV~@vAzEJ^BJRh@r@pBpBbFr@zA^t@Xh@n@bAbA`Bx@pAzBrDtCxELTfGrJ|GvKpDbGdA`BVh@n@jAx@`Bx@dBb@`A~@~BRl@Pb@z@lCpGtTPj@Lb@pBfHjBnGhAzDbKv]jAbEbDdL|BzHnAhEL^p@`C?@p@dCr@bCJb@BF\u005cvAXlAb@tBTlA@DHl@l@~DJl@j@|DpEjZr@xERxAb@pC|A|JfBxLf@fD|@`Gf@nDv@lF\u005c|B\u005cfCXvCRzBR|CLfCP`EBp@JrCTrFh@tNVhHNbEPfERvFVjHJzALfBXhCT~A`@dCj@|Bl@|BN`@Xx@@Bb@lAh@rADLh@fAh@dAVd@b@r@`A|AJNrGhIxEdGZ`@jDlEd@j@?@FFbEfFh@t@nB`CZ^NRzAlBZ^bApAxBpCnA|AhG~HHJ|ApB`AtA|@xAp@nAN\u005c`@|@bAlCnAnEl@vCFVd@rDNnA?BNfBLlCDzBH|FF|E?d@@JVbQPxGBb@H|AFv@LpBLpAVhCZpCTdBLx@t@pEl@bD|@zE?BLn@n@dDzDrSBHr@tDz@xE`AjFBNx@dETpAFXJl@v@fETnA^xBtAjHh@vCn@jDlAvGNv@`A|EXtA`@fB^pARh@FTr@nBrAvC?@bAlBfA`BbApAjDxD|H`Ih@j@pItIlAvA`@j@JNV^l@bAbAnBf@hAdArCzAhGt@vEXbBBLf@tClArHfCdPFb@z@nFXdB^~B`@`CRfAd@tCrAxGzA`G`BtFz@vCLd@b@vAbK~\u005clAxDZhATv@`A`DpAfEV|@zC|Jf@~AdAlD~@~CfCnIL^`@rANj@JXVz@b@xATr@V|@|@vC^nA\u005cdAd@~AzC`KhAtDd@|An@tBdAdDFRXdAjBdGh@fBTt@fAtDnA~DrApEVz@j@hBr@bC^tAPr@Pt@BJp@tCr@zDt@zEf@`E@Hn@pFjAhLBTfAvJz@rHpAzKRpB`AtIBXNpAh@dFFf@\u005c~CZxCTlBVpCBT@LTlBdAlJf@jENzAL|@NvA^~Cj@`FHn@?@P~AFn@Hn@~@lIp@hGb@vDNtAFn@J~@p@lGd@fE`@tD`A|I`AbJ^bDVzB^jDHt@DZ\u005c|CRfBFp@fAnJ@NFb@Hx@D\u005cHt@NtANtAPvABVD`@J|@Fh@BXRzB@TP`CN~B`@fHPtCFbALjB\u005c`Gb@fHXvEZrFNbCDp@x@jNDl@B\u005cLtBL|BHrAFlAHlARdD@\u005cFv@NbCV|D@TDx@?DLtBHlAFdALjBHxADv@NlCZ`FJlBPdCX`FJbBB^VjENjCJzAb@bHPvCX`FFz@f@vIHvAHrALvBJjBBT@XHtARpCT`EF~@Fx@JfBh@bJJzA?NLpBTlDPzCLvBRlDPrCBd@LnBPvCJ~ALvBBh@Dp@PrCF~@VbENfCF|@JtABp@R`DPrC\u005crGRfDDv@F`ALnBP|BNxANvAj@~EF^NrA^rCb@nDFb@^pCv@nGVnBh@dERdBPvAn@dFT`BlAtJr@vFrAlKx@rGLbApAbKb@pDRbB^zCFf@\u005cpCR|AZzBd@zDTbBx@xGHn@F^TnB|@fH`@zC~AjMv@jGd@vDf@~DHn@X~BL~@hCnSfBrN|@bHBPX`CR~AR`BJ|@Df@VrCdAlMv@xJ\u005cbEZbEd@rFh@|GRhC^fENlB^`EDp@RfC@JTpCZbEH|@`@fFLzAVvCd@tFd@dGV~CBTR`CH`AJnARnCLxATpCZpDXtDPpBLxBHtADrA@D@|@@x@B|A?|@?BAt@?z@A^A\u005cA|@GtAARE`AG~@Gx@?HGn@KpAKz@K|@Kv@G\u005cMt@UvAa@nBc@nBSt@St@]hAa@nAc@jAm@dBo@bBWp@EJYz@c@jAo@fB_AhCGLu@rBe@nAUp@cAxC]lAYfAi@zB[~AAFY~AYjBQ|AEZKhAMhAEn@Cb@IpAGlAInBKfCOxDInBUrFGrAMtC?@G~AEdAK`CQrE[lHWdGAPYfH?DQ`EMfDYfGOdEQbEANMtCS~ES`FI~BGbCErBCzA?jAAdA?bA?jD@nA@jA@`@BpADvBDvAFvADbAFpADv@PlC@NPvBDb@Fv@Hv@RpBRhB\u005chCT|APlAPhAl@nD`@rBDP^~AlAzFZtAhAhFBJrBnJn@xCXlAZzAjAfFXvAr@`D\u005c~A@Dp@rCHXLf@XbAb@~Az@lCp@nBZ|@@Db@dAVn@Xp@b@~@t@dBzAfD`@|@Td@j@rAN\u005cbCvFP`@tA~Cj@nAhExJt@nB`@rA^tAFVJ^Np@^nBPfAj@|DBP\u005c|BHl@LpAH`ALbBFlAB`AB`B@hBDrJ@pH@R@jH@x@@~D@fDBbDDxBFvAFdAFp@NfBL`ANhATpAJh@Ll@?BXlA^xA`@pA\u005cbAVr@N`@h@jABF\u005ct@j@bAh@bApBnD~BlEbAjB~B|Ed@fAn@~AP`@f@rAnBhG\u005cvAV|@r@lCr@xCZtAT~@vAhGH^f@~BLh@vAjGbBhHR|@nAfFJ^H`@`AhEt@~Cv@rD`ApEt@vDX`BRlAH`@p@hEPpAHn@RpAf@fEj@dFt@lIVrC^`E^zD`@hEDp@RrBFp@Dd@RvBVvCT~BFn@JbALlAFn@@NTfCTlCDb@P|BJ|AHrADtAFtADvA@nA@p@@r@@t@?z@?rA?bAAv@Ad@?VAXAp@CfAE~@GrAE`AEfAGbAMvAKvAI|@MlAS`BK|@Kp@SrAMz@SjAOv@Ov@Or@Ot@[pAYnAOt@UbAMd@a@jBc@lBa@fBQn@Qv@YnA[tAa@hB[pAYpAYpAYnAWlAu@fDWlAWtAMl@Gd@E\u005cCPMdAGj@Gj@I~@Cf@Cf@CZC~@Cv@ExA?vA@vA?V@|@B`AD`AFfAF|@BRH|@J`APtAPlAN`Ah@dDJn@Hn@BHl@~DdA`H\u005cxBn@|Dn@jEnAzHRnARpAfAnHjC`QbClOvBvMxD~UzBfN`DbSn@zDN`Ah@hD|DrVRhAf@`Dn@zDb@jCn@|DbAhGBN`DfRfErW^~BVnBJ~@NnAHz@Fj@@NHz@HlAF~@Bd@@RF`ALfDPlDl@tMv@`QFv@?@Br@l@pMLxCRdE@NFbBD`AF`APbEF~@?JDx@FxAP~DFrBJfCDpAZxINbDJpCPnDJ`CHxBNvCTdFL|CJbCNlDN|CP~DLpCNxCL|B@b@P`D@FNrCBh@LrCDp@LxCZhHhAvWXlGVvFxAj\u005cN`DFhAL|BB^B^PdCT`DFt@LnA@NRzBJx@LpADb@D\u005cThBTjB\u005cdC`@tCJx@n@vELfA~@tGrAxJ@JfAbIFf@vAhK`AhHjBhNf@lD\u005cfCfBrM~CpUNnAL|@^nCh@xDrAvJv@xFh@|DZ|BbAnH~@|GR|AjGtd@Fd@ZxBXrBhCrRtC`TnBrNr@lFdAzHBPrBbOLx@l@|Dv@jFxDfYBP~AlLh@|D~@~GrBjOxCnT|Eh^Jn@R~A~BzPhAlI~Ej^|AfLt@rFHn@~AjLPlAl@nEHn@tA|JDZvBxOjAtIXrBZxBr@lFn@xEfBjMFd@jB~Mr@jFh@~D~@|GHn@~@|GrBlOl@rEnBvN\u005c|BVnBr@lFd@rD|AzKn@zEh@~DtBjOPlAvClTpFz`@Lz@lC`SlAtIXxBZ|Bl@pEn@pEv@zFd@bD`@xCVhBl@jED^D\u005ct@lFJr@h@xDBTl@hE@Nt@lF~AnLHj@t@lFHn@VjBT`Bh@zDn@xEz@jGfAdI~@|G~@|GtA|JHn@zEx]t@pFn@rEz@lGl@pEl@jEh@vDPvAHn@RxAr@zFl@dFbAdIh@lEFh@p@nFn@hF|@jHR`Bh@fEDb@lA|J`A|HbBdNlBzO~BnRvAbLlA`KJx@z@bHx@zGt@`GX|BbAnIHj@dArIHn@L~@nAfKhAhJ@@|@nHLfAd@rD`@`Db@lDBZTjBZbCJ~@|@dHpE`_@~BhRdBhNf@~DBNr@vF|AlMh@lEh@fETnBn@rFR|A~@vHVvBFf@dAtIfAzIb@lDPtAhAlJVpBrAvK~AfM\u005cnC`@~CZ`C`DdXtBzPHn@PrAnAhKz@`HnB`P`@lD@FZbD~@bLb@vFVlDL|BPzCDp@Br@NlDLhDDpADpAHxC@J@b@DrAFnBEt@DbALhEDhA@RDp@B~@F`BFdCL`EBp@HrCJtCh@jRDjAFvAHlC@PFpB@b@HzBN~ERhHZjKRjHD|@BnALfEVhHLdE\u005cfKVpJ@JXnJ?R\u005czKRzGT`JHzBLfERlF@FTtFRbEN|BNzBB\u005cLrB@HP~B@HDn@Fl@XdDFr@Hp@JfAZvCHp@Hp@TnB`@`D\u005chCb@bDVhB^~BV~ATvAd@dCz@xEp@hDXrABJd@tB@D`@hBh@vB|B`Jv@pCPj@t@hCn@zBz@rC`ArC`AvCtAtDfAvCr@jBFJjC`H|FdOp@dBdArCvCpHTl@z@zB`@dAvAnDBF|@`CVl@f@tAl@dBZ`A\u005chA\u005cjA@Dh@rBVdAT`ADPh@fCR`A`@hCVfBVlBJ`APfB\u005c|Et@zKdAzOFbAVpDHhAj@|JXhEl@zId@zHr@fKXbE^zFLdBLpBHlAd@lHb@`Hf@pHL`BZbFFbAFp@TlDr@|KR~Cv@lLHrAXdEvA|TBZ^tFXxEHfAPjCXpEl@dJl@fJb@vGF|@|@jNZ~Ed@zGb@|Gb@zGt@dLBf@RtCJbBFx@TdD`@lGNvBF`AXlEPlC\u005chFJvAR`DTpD`@fGRzC\u005cjFh@hIN|BHfAR~CZbF^xFB^T`D?@PlCDv@Fv@FrAFzADxA@lA@bA@hA?p@?p@Az@AbAA|@C`AAl@GtAKhBOfC[nDc@lDc@nCa@`COp@Qx@Qv@Qt@Ol@W`Ac@|A]dAc@rAm@bBUf@c@bAKV_@z@Yj@INa@|@g@|@OT[j@e@v@?@qGhKMReCbE_AxAy@|AU`@}@fBGNUd@]p@qBrEmAxCcB~E_BfFUr@qAdFa@fBg@zBk@rCk@`DSrAO~@_@hCQ|AUlBe@zEEh@MtAIbAUfDUnFI`BGlCErDArBAR?rFBlFDhCB|@DvANvCJ`CLdBBf@PjCThCd@pEf@`EZ|BLx@Lx@~@|GfAtHvCxS`AzGbAhHL|@@DFd@PdAt@lFlB`NvAzJdApHL~@DRpAfJF^^tC^lCLbALv@@J\u005c|B`AzGvAzJ`@pCHj@@BFf@b@zCj@|Dj@zDtAzJN`AD\u005cFd@TzAh@bDf@jCbBhIv@rDlAzFh@lC\u005c|AH\u005cBPh@dC|@jEpAhGx@xDv@dETfAl@~CTpAb@`CHh@lAvHlArIlAlItAtJlBzMvAzJf@nDjAjIT~Av@jFvA~Jh@|D`@lCt@lFjAlInB|Mh@|Dr@xE`AzGf@tDZrBVhBh@pDPjA\u005cdCHl@l@~DR|Ad@bDVlBRzARfBVxCH~@HrA@PFbAFrAFrADfBFlD@~@?L?pA?tAAlAAvAGxCGpCGxCE`C_@lNG~FSbJUlKEnDe@tSMnFE~BAd@WpKAp@QvGGtBGnDGhD[nKa@jKGrACp@C\u005cGtBEbBCvBC`D@bA?nADzCHjDLlCNnCNtBPlBvAxMFj@v@vIdApMx@xJ\u005cnEb@vFpA`NV|B\u005cxCf@dEl@jEz@fG~@~F|@fFx@pE`BhIHd@p@`DxBvKlArHJn@Ll@VvAf@`Dv@|Er@rEdAxGJn@l@zDf@zCPlALt@v@dF`DpSx@jF`@pC`@tC\u005clCDRf@bE|@vHp@|FF`@p@vGpArKl@|Ej@|E|AnKj@|Dt@~E@Lp@zDl@pDTrA`@lCv@vEPnAr@bERtAzAjJf@bDj@jDfAlHR|A`@pCRzAj@lEd@hDdBrNL`AXzB`ApIv@zGx@bHFh@Ff@D\u005cDZr@hG?@bBxNtCrVtAfMp@|FLbAVtBLbALp@RlAXbB@DJl@Pt@\u005crANh@L`@p@tBdBzEd@rArBzFfCdHvA~D~AlEbDbJRh@JVRj@h@|ATt@r@jBd@nA\u005c|@l@`Bh@tA^dAt@nBXv@HT`@lA@DTj@Pj@
p406
ssVduration
p407
(dp408
Vtext
p409
V3 hours 54 mins
p410
sVvalue
p411
I14036
ssVend_location
p412
(dp413
Vlat
p414
F43.8394068
sVlng
p415
F-79.0697651
ssa(dp416
Vhtml_instructions
p417
VKeep <b>left</b> at the fork to continue on <b>Ontario 401 Express</b>
p418
sVdistance
p419
(dp420
Vtext
p421
V23.3 km
p422
sVvalue
p423
I23278
ssVmaneuver
p424
Vfork-left
p425
sVduration
p426
(dp427
Vtext
p428
V13 mins
p429
sVvalue
p430
I760
ssVtravel_mode
p431
VDRIVING
p432
sVpolyline
p433
(dp434
Vpoints
p435
VikqjG`iraNf@|@\u005cz@HR\u005cfAZ`Ab@lANb@Ph@Rj@Vt@N`@Rl@\u005c~@\u005cz@DLt@pB|AhEl@dBRj@hCfHfCfHrDbKzAfEd@rARh@fFvN@Bl@`BhCjHPd@lAfDb@jAPf@FTTl@zCnIRh@dCdHRh@HRjBfFPh@tI|UZ|@hA`D`BxE`ApCd@nADLxA|Dz@`CvAxD@BlAdDVv@fApC\u005cv@\u005cv@p@tAj@fAv@xAd@x@b@t@r@jAp@dAfDjFlAlBlHnLrCtEVb@bCjE@@LT@@hCvExBvDvKtRVd@fAlBLTfBfDf@`A\u005cn@hHpNxAtChC|E|AnCrBzDf@|@Zr@FXRXnA`Cp@pAn@xA~CnH\u005cr@`ApB\u005cv@~@fBFNfAxBjArBlA|BNX~AvCNVR\u005cvBvDz@vAp@hAr@hA~AjCfAdB`C|DdDlFVb@DFfBtCXb@P\u005cpArBx@xAd@z@Vd@p@vAb@dAb@dABHh@zAZfATv@Lh@Rx@Nt@Hb@X`BN`ALbAFv@Fp@Dj@HrABn@Bn@BpA@f@?f@?lA?lAE|AKxBGhACXGt@Iv@ETIp@M`AIf@Kf@SfAYpAk@dCMb@_AtD_AzDSt@U|@c@hBMb@I\u005cg@nB_@~Ae@jBg@pBOl@y@~CQr@GXGRMj@AFK`@I`@SdAMl@Kh@OdAQlAKt@Kz@Gl@Gp@Gl@El@Cb@C^AFEt@GvAAh@A^Cx@Al@?f@A|@?x@?N?d@BjABvABv@BfAB\u005cBj@Fx@F`AJ|AHbAFp@@RPvBV`D@h@^vEv@fK`AxLd@bGp@`J|@lLv@bKLxALxAFn@PrBZ~DlAzOj@fHTvCZbEjAnOvBpXDp@dAfNjB|UF~@JpAFn@`@lFLhBXtCLrAHv@Fh@DTHl@Jx@Jn@L|@TtAPz@Jh@F\u005cJf@R|@Nl@R~@^zAj@tBPn@Jh@FPNd@j@dB|@|Bh@nAb@fATd@N\u005c?@FLR^Xj@BDj@hAxAvCnAjCh@fAv@dBlAlCd@hAb@dAZz@Rh@Rj@Z`A\u005cdAJZv@lCRt@^rAj@~Bz@vDbAjENx@ZrALl@ZzA`AvEX|AZ~Ah@pCBJZdBp@pDbAbGLv@N~@P~@Hj@@@Fd@VzA`@nCRrARvAbAlHRrAVrBj@nE@HX`CJ|@p@|FJz@Df@@^~@zHbA|Ij@bFrB`Rl@nFz@nHx@jHf@lEdAvI?@\u005czCFl@LhA`@nDX`Cn@zFXdCR`Bh@pEX|BHp@ZhCJr@^|CVhBt@xFPlA?@L~@Jl@L|@J|@H`@D\u005cBPtAzJBRn@hEL~@N|@RxAp@vEBJNdARrARvANdAn@jENfABRBLNbAJp@RpA~AzKBTDXDTbBhLv@tF^fC^fCp@vEt@dF?Bv@hF|E|\u005c|@dGJr@|@lGh@lDRvAL|@PfAb@~CXhBHr@\u005c|BDRb@~Cf@jD^nCVtBRvBDn@Fn@Fz@B^J~AJdD@JD~A@\u005c@d@@b@@xABtA@hMBhLDvT@zB?x@?dA?r@@z@?|ADpE?DBvCBdABtB?@DvBBfB@V
p436
ssVstart_location
p437
(dp438
Vlat
p439
F43.8394068
sVlng
p440
F-79.0697651
ssVend_location
p441
(dp442
Vlat
p443
F43.7681599
sVlng
p444
F-79.33022419999999
ssa(dp445
Vhtml_instructions
p446
VTake the <b>ON-404</b>/<b>Don Valley Parkway</b> exit toward <b>Downtown</b>/<b>Centre-Ville</b>
p447
sVdistance
p448
(dp449
Vtext
p450
V0.4 km
p451
sVvalue
p452
I367
ssVmaneuver
p453
Vramp-right
p454
sVduration
p455
(dp456
Vtext
p457
V1 min
p458
sVvalue
p459
I17
ssVtravel_mode
p460
VDRIVING
p461
sVpolyline
p462
(dp463
Vpoints
p464
V_ncjGzdecNMb@?BAB?D?P?lD?N?R?f@AVAXAVATCRAFG^CNGTI^I`@EP_@dBEN]tAABKb@E\u005c
p465
ssVstart_location
p466
(dp467
Vlat
p468
F43.7681599
sVlng
p469
F-79.33022419999999
ssVend_location
p470
(dp471
Vlat
p472
F43.7689806
sVlng
p473
F-79.3345713
ssa(dp474
Vhtml_instructions
p475
VKeep <b>left</b> at the fork, follow signs for <b>Don Valley Parkway</b>/<b>Downtown/Centre-ville</b> and merge onto <b>Don Valley Pkwy S</b>
p476
sVdistance
p477
(dp478
Vtext
p479
V11.6 km
p480
sVvalue
p481
I11579
ssVmaneuver
p482
Vfork-left
p483
sVduration
p484
(dp485
Vtext
p486
V9 mins
p487
sVvalue
p488
I527
ssVtravel_mode
p489
VDRIVING
p490
sVpolyline
p491
(dp492
Vpoints
p493
VcscjG``fcN[pAQx@U`AQx@On@CPCLCNAJAJALAZAV?H?H?P@J?L@NBVBPBRFVFRBF@DBFHNZd@JLJLLJDDDDPJFDD@B@JDJDJ@FBL@J@P@P?Z@\u005c?`@A`@A^C\u005cE^Gn@KZGTGLA\u005cAj@Qv@Ut@UfA]l@UfA]|@[h@ONEr@Sx@SXIVGRE|@ORCPCr@MXETEdCa@bAOtB[xCe@jG_Ax@Oz@Mn@Mn@K|A]j@O@?^KhBg@`Be@r@Sj@OhBc@z@Q~Cm@RElBYfBUl@Gl@InAKbAIp@E\u005cCrAGH?v@Er@Cx@CtAEfEOnAGhAKl@En@IzASB?d@I`AMd@Ir@K^GPGJCp@Kb@IXG^Gj@I`@G`@GNCVEb@Gj@KZCXERCb@EzAGj@ClBEL?NA^?|A?`A@^?^?J?H?\u005cD\u005c?R?j@?|@@F?pB?lAAfAEx@EvEc@`AKfDc@l@I|Cc@LEJA~@OlC_@NCl@GvAQnAKb@ElBQhD[j@GRAPC~@GlAIf@?jCGL?hACbACbAADAtA?t@An@Ar@CvBEhAEx@Af@A`@A`AE|@INAh@G\u005cEPCNCXEtAUv@Uh@Md@MREx@WPIhA]t@[v@]t@_@TMZQ~@k@d@YTQJEHIxAeARORQj@a@~@s@h@c@d@]ZUXUXSn@e@n@g@ZU`@WFEPKVOTKPIVK\u005cMZKTGLCJCZEVETCB?PA^C`@?^?\u005c@ZBB?N@^D^FVF`@J`@LZLd@Rb@VVNHFFDJFNLLJJH@@NNLLLLBBRTX\u005c\u005cb@v@jA~A~BZf@|@pAb@r@b@p@j@v@p@bAd@l@p@t@d@d@b@`@\u005cTVP@?LHNHLF`@Ph@RZHj@PRDn@Hn@Hx@Lx@JzAPlEj@d@HB@\u005cHPBPF`@J\u005cJd@P\u005cPRJNJ^Tb@^VVVX\u005c^^f@@@LTRZJPDHZp@LXN\u005cPh@ZbALf@J\u005c?BL`@\u005cpAV~@FTPz@JZHXTl@Tn@Pb@JTXj@R^HNR\u005cLPTXXb@@@l@|@l@x@h@r@R`@^h@\u005ch@Xh@PZRb@Pd@@BJXNd@Nh@Rr@Nl@Jn@Jx@Fl@Fj@D|@@Z@r@?p@?n@?BA^A^A^Ex@IdAIdA?@YdD]dEANEd@En@AJEl@?@Cp@Ct@ArA?H?p@Bp@Bp@Dn@@LDb@BNFh@Fb@?@Jh@Jd@@HJ^J`@Nf@Tp@L\u005cN\u005cP\u005cBFFLLT@@PX^j@Xb@Z`@Z`@lB`CFFdApAfArAp@z@PRd@j@h@p@d@l@LNzBpCNN|AnBNPPVVXLNLNLLJLRTb@b@RPRRTRZV\u005cXVRVP@@NJNJNJZPRLNH\u005cRb@RPHVLz@^j@Rn@RZH`@J`@Jb@Jb@HVD^FL@b@FTBf@Dl@Bp@Bp@@t@@rABV@\u005c@r@Bb@DNB@?XDPBNDRDXH^J^NPFp@VjBr@
p494
ssVstart_location
p495
(dp496
Vlat
p497
F43.7689806
sVlng
p498
F-79.3345713
ssVend_location
p499
(dp500
Vlat
p501
F43.6837468
sVlng
p502
F-79.3618292
ssa(dp503
Vhtml_instructions
p504
VTake the <b>Bayview Avenue</b> exit toward <b>Bloor St</b>
p505
sVdistance
p506
(dp507
Vtext
p508
V0.7 km
p509
sVvalue
p510
I703
ssVmaneuver
p511
Vramp-right
p512
sVduration
p513
(dp514
Vtext
p515
V1 min
p516
sVvalue
p517
I43
ssVtravel_mode
p518
VDRIVING
p519
sVpolyline
p520
(dp521
Vpoints
p522
Vm~riGljkcNBJ@BBBPJFDDDJFHHHHFJDFDDDFDHFHFNDHFNFNJ^Rh@BJHLJTDLFJPZ@@JNJLNLRPNJLFPFhChAXNRLJHLLFFHHNTNTJPn@hAl@fAfCnENVPXTb@Vb@
p523
ssVstart_location
p524
(dp525
Vlat
p526
F43.6837468
sVlng
p527
F-79.3618292
ssVend_location
p528
(dp529
Vlat
p530
F43.6791192
sVlng
p531
F-79.36751129999999
ssa(dp532
Vhtml_instructions
p533
VKeep <b>left</b> at the fork to continue toward <b>Castle Frank Rd</b>
p534
sVdistance
p535
(dp536
Vtext
p537
V0.1 km
p538
sVvalue
p539
I121
ssVmaneuver
p540
Vfork-left
p541
sVduration
p542
(dp543
Vtext
p544
V1 min
p545
sVvalue
p546
I8
ssVtravel_mode
p547
VDRIVING
p548
sVpolyline
p549
(dp550
Vpoints
p551
VoariG|mlcNt@pAXh@Zh@d@x@
p552
ssVstart_location
p553
(dp554
Vlat
p555
F43.6791192
sVlng
p556
F-79.36751129999999
ssVend_location
p557
(dp558
Vlat
p559
F43.67839050000001
sVlng
p560
F-79.3686324
ssa(dp561
Vhtml_instructions
p562
VKeep <b>left</b>, follow signs for <b>Bloor St E</b>/<b>Danforth Ave</b>
p563
sVdistance
p564
(dp565
Vtext
p566
V0.6 km
p567
sVvalue
p568
I580
ssVmaneuver
p569
Vkeep-left
p570
sVduration
p571
(dp572
Vtext
p573
V1 min
p574
sVvalue
p575
I51
ssVtravel_mode
p576
VDRIVING
p577
sVpolyline
p578
(dp579
Vpoints
p580
V}|qiG|tlcNFD?@DFLPHLHFHHHFDBDBFBF@NFJ@H@F?H?H?DA@?DADALCDCDAFEDCBCHGJKFIFGBEHMT]`@m@^k@PW\u005ci@HM\u005ce@LSJM@ADIFGFEDCBCBABCDA@A@?BCFAHCBAD?HAD?BAH@F?F?B@B?JBB@FBFBHBFFFDDFDB@BBDLNFJDJBD@BHZLh@VjBDV
p581
ssVstart_location
p582
(dp583
Vlat
p584
F43.67839050000001
sVlng
p585
F-79.3686324
ssVend_location
p586
(dp587
Vlat
p588
F43.6744798
sVlng
p589
F-79.3685768
ssa(dp590
Vhtml_instructions
p591
VTurn <b>left</b> onto <b>Castle Frank Rd</b>
p592
sVdistance
p593
(dp594
Vtext
p595
V88 m
p596
sVvalue
p597
I88
ssVmaneuver
p598
Vturn-left
p599
sVduration
p600
(dp601
Vtext
p602
V1 min
p603
sVvalue
p604
I19
ssVtravel_mode
p605
VDRIVING
p606
sVpolyline
p607
(dp608
Vpoints
p609
VodqiGrtlcNB@@@B@@?D?DCJERKHGRKZUZU
p610
ssVstart_location
p611
(dp612
Vlat
p613
F43.6744798
sVlng
p614
F-79.3685768
ssVend_location
p615
(dp616
Vlat
p617
F43.6737695
sVlng
p618
F-79.3681754
ssa(dp619
Vhtml_instructions
p620
VTurn <b>left</b> onto <b>Bloor St E</b>
p621
sVdistance
p622
(dp623
Vtext
p624
V0.6 km
p625
sVvalue
p626
I613
ssVmaneuver
p627
Vturn-left
p628
sVduration
p629
(dp630
Vtext
p631
V1 min
p632
sVvalue
p633
I56
ssVtravel_mode
p634
VDRIVING
p635
sVpolyline
p636
(dp637
Vpoints
p638
Va`qiGbrlcNUa@U_@u@kAe@u@KOGOIQAECICGAIAEAIGe@m@iFIq@[mCo@oFQyAI{@[}CE_@Iq@
p639
ssVstart_location
p640
(dp641
Vlat
p642
F43.6737695
sVlng
p643
F-79.3681754
ssVend_location
p644
(dp645
Vlat
p646
F43.675739
sVlng
p647
F-79.361226
ssa(dp648
Vhtml_instructions
p649
VContinue onto <b>Danforth Ave</b>
p650
sVdistance
p651
(dp652
Vtext
p653
V0.3 km
p654
sVvalue
p655
I341
ssVtravel_mode
p656
VDRIVING
p657
sVstart_location
p658
(dp659
Vlat
p660
F43.675739
sVlng
p661
F-79.361226
ssVpolyline
p662
(dp663
Vpoints
p664
VklqiGtfkcNCUCUGk@Io@E]Ge@CSE]KaAMoAKu@CY[eCKcAMgAMaA
p665
ssVduration
p666
(dp667
Vtext
p668
V1 min
p669
sVvalue
p670
I70
ssVend_location
p671
(dp672
Vlat
p673
F43.6765373
sVlng
p674
F-79.3571336
ssasVstart_location
p675
(dp676
Vlat
p677
F45.51715249999999
sVlng
p678
F-73.57983089999999
ssVend_location
p679
(dp680
Vlat
p681
F43.6765373
sVlng
p682
F-79.3571336
ssasa.